package eus.avallende.lanabeus.model.zenbaki

import kotlin.test.Test
import kotlin.test.assertEquals

class ZenbakiTest {
    @Test
    fun testZifrakLetretan() {
        assertEquals(ZenbakiConstants.LETRETAN_0, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_0))
        assertEquals(ZenbakiConstants.LETRETAN_1, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_1))
        assertEquals(ZenbakiConstants.LETRETAN_2, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_2))
        assertEquals(ZenbakiConstants.LETRETAN_3, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_3))
        assertEquals(ZenbakiConstants.LETRETAN_4, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_4))
        assertEquals(ZenbakiConstants.LETRETAN_5, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_5))
        assertEquals(ZenbakiConstants.LETRETAN_6, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_6))
        assertEquals(ZenbakiConstants.LETRETAN_7, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_7))
        assertEquals(ZenbakiConstants.LETRETAN_8, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_8))
        assertEquals(ZenbakiConstants.LETRETAN_9, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_9))
        assertEquals(ZenbakiConstants.LETRETAN_10, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_10))
        assertEquals(ZenbakiConstants.LETRETAN_11, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_11))
        assertEquals(ZenbakiConstants.LETRETAN_12, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_12))
        assertEquals(ZenbakiConstants.LETRETAN_13, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_13))
        assertEquals(ZenbakiConstants.LETRETAN_14, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_14))
        assertEquals(ZenbakiConstants.LETRETAN_15, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_15))
        assertEquals(ZenbakiConstants.LETRETAN_16, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_16))
        assertEquals(ZenbakiConstants.LETRETAN_17, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_17))
        assertEquals(ZenbakiConstants.LETRETAN_18, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_18))
        assertEquals(ZenbakiConstants.LETRETAN_19, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_19))
        assertEquals(ZenbakiConstants.LETRETAN_20, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_20))
        assertEquals(ZenbakiConstants.LETRETAN_21, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_21))
        assertEquals(ZenbakiConstants.LETRETAN_22, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_22))
        assertEquals(ZenbakiConstants.LETRETAN_30, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_30))
        assertEquals(ZenbakiConstants.LETRETAN_31, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_31))
        assertEquals(ZenbakiConstants.LETRETAN_32, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_32))
        assertEquals(ZenbakiConstants.LETRETAN_40, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_40))
        assertEquals(ZenbakiConstants.LETRETAN_47, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_47))
        assertEquals(ZenbakiConstants.LETRETAN_50, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_50))
        assertEquals(ZenbakiConstants.LETRETAN_58, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_58))
        assertEquals(ZenbakiConstants.LETRETAN_60, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_60))
        assertEquals(ZenbakiConstants.LETRETAN_70, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_70))
        assertEquals(ZenbakiConstants.LETRETAN_80, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_80))
        assertEquals(ZenbakiConstants.LETRETAN_90, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_90))
        assertEquals(ZenbakiConstants.LETRETAN_95, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_95))
        assertEquals(ZenbakiConstants.LETRETAN_100, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_100))
        assertEquals(ZenbakiConstants.LETRETAN_101, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_101))
        assertEquals(ZenbakiConstants.LETRETAN_127, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_127))
        assertEquals(ZenbakiConstants.LETRETAN_200, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_200))
        assertEquals(ZenbakiConstants.LETRETAN_240, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_240))
        assertEquals(ZenbakiConstants.LETRETAN_300, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_300))
        assertEquals(ZenbakiConstants.LETRETAN_400, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_400))
        assertEquals(ZenbakiConstants.LETRETAN_500, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_500))
        assertEquals(ZenbakiConstants.LETRETAN_600, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_600))
        assertEquals(ZenbakiConstants.LETRETAN_700, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_700))
        assertEquals(ZenbakiConstants.LETRETAN_731, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_731))
        assertEquals(ZenbakiConstants.LETRETAN_800, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_800))
        assertEquals(ZenbakiConstants.LETRETAN_881, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_881))
        assertEquals(ZenbakiConstants.LETRETAN_900, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_900))
    }

    @Test
    fun testZifrakLetretanHamarBainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_1, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_1))
        assertEquals(ZenbakiConstants.LETRETAN_2, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_2))
        assertEquals(ZenbakiConstants.LETRETAN_3, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_3))
        assertEquals(ZenbakiConstants.LETRETAN_4, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_4))
        assertEquals(ZenbakiConstants.LETRETAN_5, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_5))
        assertEquals(ZenbakiConstants.LETRETAN_6, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_6))
        assertEquals(ZenbakiConstants.LETRETAN_7, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_7))
        assertEquals(ZenbakiConstants.LETRETAN_8, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_8))
        assertEquals(ZenbakiConstants.LETRETAN_9, Zenbaki.zifrakLetretanHamarBainoGutxiago(ZenbakiConstants.ZIFRETAN_9))
    }

    @Test
    fun testLetretanEhunBainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_10, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_10))
        assertEquals(ZenbakiConstants.LETRETAN_11, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_11))
        assertEquals(ZenbakiConstants.LETRETAN_12, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_12))
        assertEquals(ZenbakiConstants.LETRETAN_13, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_13))
        assertEquals(ZenbakiConstants.LETRETAN_14, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_14))
        assertEquals(ZenbakiConstants.LETRETAN_15, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_15))
        assertEquals(ZenbakiConstants.LETRETAN_16, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_16))
        assertEquals(ZenbakiConstants.LETRETAN_17, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_17))
        assertEquals(ZenbakiConstants.LETRETAN_18, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_18))
        assertEquals(ZenbakiConstants.LETRETAN_19, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_19))
        assertEquals(ZenbakiConstants.LETRETAN_20, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_20))
        assertEquals(ZenbakiConstants.LETRETAN_21, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_21))
        assertEquals(ZenbakiConstants.LETRETAN_22, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_22))
        assertEquals(ZenbakiConstants.LETRETAN_30, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_30))
        assertEquals(ZenbakiConstants.LETRETAN_31, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_31))
        assertEquals(ZenbakiConstants.LETRETAN_32, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_32))
        assertEquals(ZenbakiConstants.LETRETAN_40, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_40))
        assertEquals(ZenbakiConstants.LETRETAN_47, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_47))
        assertEquals(ZenbakiConstants.LETRETAN_50, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_50))
        assertEquals(ZenbakiConstants.LETRETAN_58, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_58))
        assertEquals(ZenbakiConstants.LETRETAN_60, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_60))
        assertEquals(ZenbakiConstants.LETRETAN_70, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_70))
        assertEquals(ZenbakiConstants.LETRETAN_80, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_80))
        assertEquals(ZenbakiConstants.LETRETAN_90, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_90))
        assertEquals(ZenbakiConstants.LETRETAN_95, Zenbaki.zifrakLetretanEhunBainoGutxiago(ZenbakiConstants.ZIFRETAN_95))
    }

    @Test
    fun testZifrakLetretanMilaBainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_100, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_100))
        assertEquals(ZenbakiConstants.LETRETAN_101, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_101))
        assertEquals(ZenbakiConstants.LETRETAN_127, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_127))
        assertEquals(ZenbakiConstants.LETRETAN_200, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_200))
        assertEquals(ZenbakiConstants.LETRETAN_240, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_240))
        assertEquals(ZenbakiConstants.LETRETAN_300, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_300))
        assertEquals(ZenbakiConstants.LETRETAN_400, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_400))
        assertEquals(ZenbakiConstants.LETRETAN_500, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_500))
        assertEquals(ZenbakiConstants.LETRETAN_600, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_600))
        assertEquals(ZenbakiConstants.LETRETAN_700, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_700))
        assertEquals(ZenbakiConstants.LETRETAN_731, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_731))
        assertEquals(ZenbakiConstants.LETRETAN_800, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_800))
        assertEquals(ZenbakiConstants.LETRETAN_881, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_881))
        assertEquals(ZenbakiConstants.LETRETAN_900, Zenbaki.zifrakLetretanMilaBainoGutxiago(ZenbakiConstants.ZIFRETAN_900))
    }

    @Test
    fun testZifrakLetretanMilioiBainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_1000, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_1000))
        assertEquals(ZenbakiConstants.LETRETAN_1123, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_1123))
        assertEquals(ZenbakiConstants.LETRETAN_1200, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_1200))
        assertEquals(ZenbakiConstants.LETRETAN_2000, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_2000))
        assertEquals(ZenbakiConstants.LETRETAN_3000, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_3000))
        assertEquals(ZenbakiConstants.LETRETAN_5456, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_5456))
        assertEquals(ZenbakiConstants.LETRETAN_7020, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_7020))
        assertEquals(ZenbakiConstants.LETRETAN_22800, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_22800))
        assertEquals(ZenbakiConstants.LETRETAN_26671, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_26671))
        assertEquals(ZenbakiConstants.LETRETAN_100300, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_100300))
        assertEquals(ZenbakiConstants.LETRETAN_500000, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_500000))
        assertEquals(ZenbakiConstants.LETRETAN_521521, Zenbaki.zifrakLetretanMilioiBainoGutxiago(ZenbakiConstants.ZIFRETAN_521521))
    }
}
