package eus.avallende.lanabeus.model.zenbaki

import kotlin.test.Test
import kotlin.test.assertEquals

class ZenbakiTest {
    @Test
    fun testZifrakLetretan() {
        assertEquals(ZenbakiConstants.LETRETAN_0, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_0))
        assertEquals(ZenbakiConstants.LETRETAN_1, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_1))
        assertEquals(ZenbakiConstants.LETRETAN_2, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_2))
        assertEquals(ZenbakiConstants.LETRETAN_3, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_3))
        assertEquals(ZenbakiConstants.LETRETAN_4, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_4))
        assertEquals(ZenbakiConstants.LETRETAN_5, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_5))
        assertEquals(ZenbakiConstants.LETRETAN_6, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_6))
        assertEquals(ZenbakiConstants.LETRETAN_7, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_7))
        assertEquals(ZenbakiConstants.LETRETAN_8, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_8))
        assertEquals(ZenbakiConstants.LETRETAN_9, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_9))
        assertEquals(ZenbakiConstants.LETRETAN_10, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_10))
        assertEquals(ZenbakiConstants.LETRETAN_11, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_11))
        assertEquals(ZenbakiConstants.LETRETAN_12, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_12))
        assertEquals(ZenbakiConstants.LETRETAN_13, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_13))
        assertEquals(ZenbakiConstants.LETRETAN_14, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_14))
        assertEquals(ZenbakiConstants.LETRETAN_15, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_15))
        assertEquals(ZenbakiConstants.LETRETAN_16, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_16))
        assertEquals(ZenbakiConstants.LETRETAN_17, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_17))
        assertEquals(ZenbakiConstants.LETRETAN_18, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_18))
        assertEquals(ZenbakiConstants.LETRETAN_19, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_19))
        assertEquals(ZenbakiConstants.LETRETAN_20, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_20))
        assertEquals(ZenbakiConstants.LETRETAN_21, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_21))
        assertEquals(ZenbakiConstants.LETRETAN_22, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_22))
        assertEquals(ZenbakiConstants.LETRETAN_30, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_30))
        assertEquals(ZenbakiConstants.LETRETAN_31, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_31))
        assertEquals(ZenbakiConstants.LETRETAN_32, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_32))
        assertEquals(ZenbakiConstants.LETRETAN_40, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_40))
        assertEquals(ZenbakiConstants.LETRETAN_47, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_47))
        assertEquals(ZenbakiConstants.LETRETAN_50, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_50))
        assertEquals(ZenbakiConstants.LETRETAN_58, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_58))
        assertEquals(ZenbakiConstants.LETRETAN_60, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_60))
        assertEquals(ZenbakiConstants.LETRETAN_70, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_70))
        assertEquals(ZenbakiConstants.LETRETAN_80, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_80))
        assertEquals(ZenbakiConstants.LETRETAN_90, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_90))
        assertEquals(ZenbakiConstants.LETRETAN_95, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_95))
        assertEquals(ZenbakiConstants.LETRETAN_100, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_100))
        assertEquals(ZenbakiConstants.LETRETAN_101, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_101))
        assertEquals(ZenbakiConstants.LETRETAN_127, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_127))
        assertEquals(ZenbakiConstants.LETRETAN_200, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_200))
        assertEquals(ZenbakiConstants.LETRETAN_240, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_240))
        assertEquals(ZenbakiConstants.LETRETAN_300, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_300))
        assertEquals(ZenbakiConstants.LETRETAN_400, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_400))
        assertEquals(ZenbakiConstants.LETRETAN_500, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_500))
        assertEquals(ZenbakiConstants.LETRETAN_600, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_600))
        assertEquals(ZenbakiConstants.LETRETAN_700, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_700))
        assertEquals(ZenbakiConstants.LETRETAN_731, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_731))
        assertEquals(ZenbakiConstants.LETRETAN_800, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_800))
        assertEquals(ZenbakiConstants.LETRETAN_881, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_881))
        assertEquals(ZenbakiConstants.LETRETAN_900, Zenbaki.zifrakLetretan(ZenbakiConstants.ZIFRETAN_900))
    }

    @Test
    fun testLetretan10BainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_1, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_1))
        assertEquals(ZenbakiConstants.LETRETAN_2, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_2))
        assertEquals(ZenbakiConstants.LETRETAN_3, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_3))
        assertEquals(ZenbakiConstants.LETRETAN_4, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_4))
        assertEquals(ZenbakiConstants.LETRETAN_5, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_5))
        assertEquals(ZenbakiConstants.LETRETAN_6, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_6))
        assertEquals(ZenbakiConstants.LETRETAN_7, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_7))
        assertEquals(ZenbakiConstants.LETRETAN_8, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_8))
        assertEquals(ZenbakiConstants.LETRETAN_9, Zenbaki.letretan10BainoGutxiago(ZenbakiConstants.ZIFRETAN_9))
    }

    @Test
    fun testLetretan100BainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_10, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_10))
        assertEquals(ZenbakiConstants.LETRETAN_11, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_11))
        assertEquals(ZenbakiConstants.LETRETAN_12, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_12))
        assertEquals(ZenbakiConstants.LETRETAN_13, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_13))
        assertEquals(ZenbakiConstants.LETRETAN_14, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_14))
        assertEquals(ZenbakiConstants.LETRETAN_15, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_15))
        assertEquals(ZenbakiConstants.LETRETAN_16, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_16))
        assertEquals(ZenbakiConstants.LETRETAN_17, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_17))
        assertEquals(ZenbakiConstants.LETRETAN_18, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_18))
        assertEquals(ZenbakiConstants.LETRETAN_19, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_19))
        assertEquals(ZenbakiConstants.LETRETAN_20, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_20))
        assertEquals(ZenbakiConstants.LETRETAN_21, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_21))
        assertEquals(ZenbakiConstants.LETRETAN_22, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_22))
        assertEquals(ZenbakiConstants.LETRETAN_30, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_30))
        assertEquals(ZenbakiConstants.LETRETAN_31, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_31))
        assertEquals(ZenbakiConstants.LETRETAN_32, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_32))
        assertEquals(ZenbakiConstants.LETRETAN_40, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_40))
        assertEquals(ZenbakiConstants.LETRETAN_47, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_47))
        assertEquals(ZenbakiConstants.LETRETAN_50, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_50))
        assertEquals(ZenbakiConstants.LETRETAN_58, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_58))
        assertEquals(ZenbakiConstants.LETRETAN_60, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_60))
        assertEquals(ZenbakiConstants.LETRETAN_70, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_70))
        assertEquals(ZenbakiConstants.LETRETAN_80, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_80))
        assertEquals(ZenbakiConstants.LETRETAN_90, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_90))
        assertEquals(ZenbakiConstants.LETRETAN_95, Zenbaki.letretan100BainoGutxiago(ZenbakiConstants.ZIFRETAN_95))
    }

    @Test
    fun testLetretan1000BainoGutxiago() {
        assertEquals(ZenbakiConstants.LETRETAN_100, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_100))
        assertEquals(ZenbakiConstants.LETRETAN_101, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_101))
        assertEquals(ZenbakiConstants.LETRETAN_127, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_127))
        assertEquals(ZenbakiConstants.LETRETAN_200, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_200))
        assertEquals(ZenbakiConstants.LETRETAN_240, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_240))
        assertEquals(ZenbakiConstants.LETRETAN_300, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_300))
        assertEquals(ZenbakiConstants.LETRETAN_400, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_400))
        assertEquals(ZenbakiConstants.LETRETAN_500, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_500))
        assertEquals(ZenbakiConstants.LETRETAN_600, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_600))
        assertEquals(ZenbakiConstants.LETRETAN_700, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_700))
        assertEquals(ZenbakiConstants.LETRETAN_731, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_731))
        assertEquals(ZenbakiConstants.LETRETAN_800, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_800))
        assertEquals(ZenbakiConstants.LETRETAN_881, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_881))
        assertEquals(ZenbakiConstants.LETRETAN_900, Zenbaki.letretan1000BainoGutxiago(ZenbakiConstants.ZIFRETAN_900))
    }
}
